# -*- coding: utf-8 -*-
"""DataScience -  Manipulação de arquivo CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPskz5eicG26v_rxkMQz9ZiR9j09s6UN

#Pandas

**Importando Pandas e pedindo para ele ler o arquivo CSV**
"""

import pandas as pd
tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb

"""**Contando a quantidade de valores de cada lingua na coluna original language**"""

tmdb["original_language"].value_counts()

"""**Transformando a contagem de valores de cada lingua em um DataFrame**

"""

tmdb["original_language"].value_counts().to_frame()

"""**Resetando o index do DataFrame**"""

total_de_valor_por_lingua = tmdb["original_language"].value_counts().to_frame().reset_index()
total_de_valor_por_lingua

"""**Mudando o nome das colunas para ficar mais claro**"""

total_de_valor_por_lingua.columns = ["lingua","total"]
total_de_valor_por_lingua

"""#Seaborn

**Importando seaborn e fazendo um histograma de total_de_valor_por_lingua**
"""

import seaborn as sns
sns.barplot(x="lingua",y="total",data=total_de_valor_por_lingua)

"""**Fazendo uma lógica para comparar o total de inglês com o total das outras linguas**"""

total_de_todos=tmdb["original_language"].value_counts()
total_de_geral = total_de_todos.sum()
total_de_ingles = total_de_todos.loc["en"]
total_do_resto = total_de_geral - total_de_ingles

"""**Dicionário com as informações anteriores**"""

dados = {
      "lingua":["ingles","resto"],
      "total":[total_de_ingles,total_do_resto]
}
dados

"""**Transformando o dicionário dados em um DataFrame**"""

pd.DataFrame(dados)

"""**fazendo um histograma de dados**"""

sns.barplot(x="lingua",y="total",data=dados)

"""**Comparando as linguas sem o ingles e vendo o valor de cada uma**"""

total_de_linguas_sem_ingles = tmdb.query("original_language != 'en'")["original_language"].value_counts().to_frame().reset_index()
total_de_linguas_sem_ingles.columns = ["original_language","total"]
total_de_linguas_sem_ingles

"""**fazendo um histograma das linguas sem o ingles**"""

sns.barplot(x="original_language",y="total",data=total_de_linguas_sem_ingles)